// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webshop_Berchtold.Data;

#nullable disable

namespace Webshop_Berchtold.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105083423_AddProductSeedData")]
    partial class AddProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("BildUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschreibung = "Schrauben, Nägel, Dübel und andere Verbindungselemente",
                            Name = "Schrauben und Verbindungen"
                        },
                        new
                        {
                            Id = 2,
                            Beschreibung = "Konstruktionsholz, Balken, Bretter und Latten",
                            Name = "Balken und Bretter"
                        },
                        new
                        {
                            Id = 3,
                            Beschreibung = "Handwerkzeuge und Elektrowerkzeuge für Holzbau",
                            Name = "Werkzeuge"
                        },
                        new
                        {
                            Id = 4,
                            Beschreibung = "Isoliermaterialien für Wärme- und Schalldämmung",
                            Name = "Dämmstoffe"
                        },
                        new
                        {
                            Id = 5,
                            Beschreibung = "Lasuren, Beizen und Schutzanstriche für Holz",
                            Name = "Holzschutz"
                        });
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BestellDatum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<decimal>("GesamtBetrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Land")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LieferAdresse")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postleitzahl")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stadt")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anzahl")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EinzelPreis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anzahl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BildUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstellungsDatum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IstVerfuegbar")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KategorieId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anzahl = 100,
                            Beschreibung = "Edelstahl A2, rostfrei, Teilgewinde für optimalen Halt",
                            BildUrl = "/images/products/screws1.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 577, DateTimeKind.Local).AddTicks(387),
                            IstVerfuegbar = true,
                            KategorieId = 1,
                            Name = "Holzschrauben Premium 6x80mm",
                            Preis = 24.99m
                        },
                        new
                        {
                            Id = 2,
                            Anzahl = 50,
                            Beschreibung = "Verzinkte Balkenschuhe für sichere Holzverbindungen",
                            BildUrl = "/images/products/beam-shoes.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(900),
                            IstVerfuegbar = true,
                            KategorieId = 1,
                            Name = "Balkenschuhe 80x120mm",
                            Preis = 8.50m
                        },
                        new
                        {
                            Id = 3,
                            Anzahl = 30,
                            Beschreibung = "Verzinkte Gewindestangen verschiedene Längen für Holzkonstruktionen",
                            BildUrl = "/images/products/threaded-rods.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(953),
                            IstVerfuegbar = true,
                            KategorieId = 1,
                            Name = "Gewindestangen M12",
                            Preis = 15.60m
                        },
                        new
                        {
                            Id = 4,
                            Anzahl = 200,
                            Beschreibung = "Verschiedene Größen für optimale Kraftverteilung",
                            BildUrl = "/images/products/washers.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(958),
                            IstVerfuegbar = true,
                            KategorieId = 1,
                            Name = "Unterlegscheiben Set",
                            Preis = 5.90m
                        },
                        new
                        {
                            Id = 5,
                            Anzahl = 80,
                            Beschreibung = "Trockenes Fichtenholz, kammergetrocknet für tragende Zwecke",
                            BildUrl = "/images/products/construction-wood.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(962),
                            IstVerfuegbar = true,
                            KategorieId = 2,
                            Name = "Konstruktionsholz 60x120mm",
                            Preis = 8.90m
                        },
                        new
                        {
                            Id = 6,
                            Anzahl = 120,
                            Beschreibung = "Gehobelte Fichtenbretter für Schalung und Verkleidung",
                            BildUrl = "/images/products/boards.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(965),
                            IstVerfuegbar = true,
                            KategorieId = 2,
                            Name = "Bretter 24x200mm",
                            Preis = 12.50m
                        },
                        new
                        {
                            Id = 7,
                            Anzahl = 40,
                            Beschreibung = "Verleimte Fichtenbinder für tragende Zwecke im Holzbau",
                            BildUrl = "/images/products/glulam-beams.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(968),
                            IstVerfuegbar = true,
                            KategorieId = 2,
                            Name = "Leimholzbalken 100x200mm",
                            Preis = 28.90m
                        },
                        new
                        {
                            Id = 8,
                            Anzahl = 60,
                            Beschreibung = "Orientierte Spanplatten 2500x1250mm für Dach und Wand",
                            BildUrl = "/images/products/osb-plates.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(971),
                            IstVerfuegbar = true,
                            KategorieId = 2,
                            Name = "OSB-Platten 18mm",
                            Preis = 34.90m
                        },
                        new
                        {
                            Id = 9,
                            Anzahl = 25,
                            Beschreibung = "Professioneller Hammer mit Eschenstiel und Nagelzieher",
                            BildUrl = "/images/products/hammer.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(974),
                            IstVerfuegbar = true,
                            KategorieId = 3,
                            Name = "Zimmermannshammer 600g",
                            Preis = 45.90m
                        },
                        new
                        {
                            Id = 10,
                            Anzahl = 15,
                            Beschreibung = "18V Li-Ion mit 2 Akkus und Ladegerät für professionelle Anwendungen",
                            BildUrl = "/images/products/cordless-drill.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(977),
                            IstVerfuegbar = true,
                            KategorieId = 3,
                            Name = "Akkuschrauber Set",
                            Preis = 189.90m
                        },
                        new
                        {
                            Id = 11,
                            Anzahl = 35,
                            Beschreibung = "Präzisionswinkel für exakte Messungen im Holzbau",
                            BildUrl = "/images/products/square.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(980),
                            IstVerfuegbar = true,
                            KategorieId = 3,
                            Name = "Zimmermannswinkel 600mm",
                            Preis = 29.90m
                        },
                        new
                        {
                            Id = 12,
                            Anzahl = 20,
                            Beschreibung = "Aluminium-Wasserwaage mit 3 Libellen für präzises Arbeiten",
                            BildUrl = "/images/products/level.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(983),
                            IstVerfuegbar = true,
                            KategorieId = 3,
                            Name = "Wasserwaage 1200mm",
                            Preis = 67.90m
                        },
                        new
                        {
                            Id = 13,
                            Anzahl = 45,
                            Beschreibung = "Wetterschutzlasur für Außenholz mit UV-Schutz",
                            BildUrl = "/images/products/wood-stain.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(987),
                            IstVerfuegbar = true,
                            KategorieId = 5,
                            Name = "Holzlasur Nussbaum 5L",
                            Preis = 49.90m
                        },
                        new
                        {
                            Id = 14,
                            Anzahl = 60,
                            Beschreibung = "Natürliches Holzöl für Terrassen und Gartenmöbel",
                            BildUrl = "/images/products/wood-oil.jpg",
                            ErstellungsDatum = new DateTime(2025, 11, 5, 9, 34, 22, 580, DateTimeKind.Local).AddTicks(990),
                            IstVerfuegbar = true,
                            KategorieId = 5,
                            Name = "Holzöl Teak 2,5L",
                            Preis = 38.50m
                        });
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anzahl")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HinzugefuegtAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrierungsDatum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Webshop_Berchtold.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Webshop_Berchtold.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop_Berchtold.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Webshop_Berchtold.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.Order", b =>
                {
                    b.HasOne("Webshop_Berchtold.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.OrderItem", b =>
                {
                    b.HasOne("Webshop_Berchtold.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop_Berchtold.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.Product", b =>
                {
                    b.HasOne("Webshop_Berchtold.Models.Category", "Kategorie")
                        .WithMany("Products")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("Webshop_Berchtold.Models.Product", "Product")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop_Berchtold.Models.User", "User")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ShoppingCartItems");
                });

            modelBuilder.Entity("Webshop_Berchtold.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ShoppingCartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
